//Pokémon array
// Gen 1 - All 151 Pokémon
const pokemon = [
  {
    natdex: "001",
    name: "Bulbasaur",
    type1: "grass",
    type2: "poison",
    imagesrc: "assets/gen-i/001Bulbasaur.png",
  },
  {
    natdex: "002",
    name: "Ivysaur",
    type1: "grass",
    type2: "poison",
    imagesrc: "assets/gen-i/002Ivysaur.png",
  },
  {
    natdex: "003",
    name: "Venusaur",
    type1: "grass",
    type2: "poison",
    imagesrc: "assets/gen-i/003Venusaur.png",
  },
  {
    natdex: "004",
    name: "Charmander",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/004Charmander.png",
  },
  {
    natdex: "005",
    name: "Charmeleon",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/005Charmeleon.png",
  },
  {
    natdex: "006",
    name: "Charizard",
    type1: "fire",
    type2: "flying",
    imagesrc: "assets/gen-i/006Charizard.png",
  },
  {
    natdex: "007",
    name: "Squirtle",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/007Squirtle.png",
  },
  {
    natdex: "008",
    name: "Wartortle",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/008Wartortle.png",
  },
  {
    natdex: "009",
    name: "Blastoise",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/009Blastoise.png",
  },
  {
    natdex: "010",
    name: "Caterpie",
    type1: "bug",
    type2: "",
    imagesrc: "assets/gen-i/010Caterpie.png",
  },
  {
    natdex: "011",
    name: "Metapod",
    type1: "bug",
    type2: "",
    imagesrc: "assets/gen-i/011Metapod.png",
  },
  {
    natdex: "012",
    name: "Butterfree",
    type1: "bug",
    type2: "flying",
    imagesrc: "assets/gen-i/012Butterfree.png",
  },
  {
    natdex: "013",
    name: "Weedle",
    type1: "bug",
    type2: "poison",
    imagesrc: "assets/gen-i/013Weedle.png",
  },
  {
    natdex: "014",
    name: "Kakuna",
    type1: "bug",
    type2: "poison",
    imagesrc: "assets/gen-i/014Kakuna.png",
  },
  {
    natdex: "015",
    name: "Beedrill",
    type1: "bug",
    type2: "poison",
    imagesrc: "assets/gen-i/015Beedrill.png",
  },
  {
    natdex: "016",
    name: "Pidgey",
    type1: "normal",
    type2: "flying",
    imagesrc: "assets/gen-i/016Pidgey.png",
  },
  {
    natdex: "017",
    name: "Pidgeotto",
    type1: "normal",
    type2: "flying",
    imagesrc: "assets/gen-i/017Pidgeotto.png",
  },
  {
    natdex: "018",
    name: "Pidgeot",
    type1: "normal",
    type2: "flying",
    imagesrc: "assets/gen-i/018Pidgeot.png",
  },
  {
    natdex: "019",
    name: "Rattata",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/019Rattata.png",
  },
  {
    natdex: "020",
    name: "Raticate",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/020Raticate.png",
  },
  {
    natdex: "021",
    name: "Spearow",
    type1: "normal",
    type2: "flying",
    imagesrc: "assets/gen-i/021Spearow.png",
  },
  {
    natdex: "022",
    name: "Fearow",
    type1: "normal",
    type2: "flying",
    imagesrc: "assets/gen-i/022Fearow.png",
  },
  {
    natdex: "023",
    name: "Ekans",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/023Ekans.png",
  },
  {
    natdex: "024",
    name: "Arbok",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/024Arbok.png",
  },
  {
    natdex: "025",
    name: "Pikachu",
    type1: "electric",
    type2: "",
    imagesrc: "assets/gen-i/025Pikachu.png",
  },
  {
    natdex: "026",
    name: "Raichu",
    type1: "electric",
    type2: "",
    imagesrc: "assets/gen-i/026Raichu.png",
  },
  {
    natdex: "027",
    name: "Sandshrew",
    type1: "ground",
    type2: "",
    imagesrc: "assets/gen-i/027Sandshrew.png",
  },
  {
    natdex: "028",
    name: "Sandslash",
    type1: "ground",
    type2: "",
    imagesrc: "assets/gen-i/028Sandslash.png",
  },
  {
    natdex: "029",
    name: "Nidoran♀",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/029Nidoran.png",
  },
  {
    natdex: "030",
    name: "Nidorina",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/030Nidorina.png",
  },
  {
    natdex: "031",
    name: "Nidoqueen",
    type1: "poison",
    type2: "ground",
    imagesrc: "assets/gen-i/031Nidoqueen.png",
  },
  {
    natdex: "032",
    name: "Nidoran♂",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/032Nidoran.png",
  },
  {
    natdex: "033",
    name: "Nidorino",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/033Nidorino.png",
  },
  {
    natdex: "034",
    name: "Nidoking",
    type1: "poison",
    type2: "ground",
    imagesrc: "assets/gen-i/034Nidoking.png",
  },
  {
    natdex: "035",
    name: "Clefairy",
    type1: "fairy",
    type2: "",
    imagesrc: "assets/gen-i/035Clefairy.png",
  },
  {
    natdex: "036",
    name: "Clefable",
    type1: "fairy",
    type2: "",
    imagesrc: "assets/gen-i/036Clefable.png",
  },
  {
    natdex: "037",
    name: "Vulpix",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/037Vulpix.png",
  },
  {
    natdex: "038",
    name: "Ninetales",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/038Ninetales.png",
  },
  {
    natdex: "039",
    name: "Jigglypuff",
    type1: "normal",
    type2: "fairy",
    imagesrc: "assets/gen-i/039Jigglypuff.png",
  },
  {
    natdex: "040",
    name: "Wigglytuff",
    type1: "normal",
    type2: "fairy",
    imagesrc: "assets/gen-i/040Wigglytuff.png",
  },
  {
    natdex: "041",
    name: "Zubat",
    type1: "poison",
    type2: "flying",
    imagesrc: "assets/gen-i/041Zubat.png",
  },
  {
    natdex: "042",
    name: "Golbat",
    type1: "poison",
    type2: "flying",
    imagesrc: "assets/gen-i/042Golbat.png",
  },
  {
    natdex: "043",
    name: "Oddish",
    type1: "grass",
    type2: "poison",
    imagesrc: "assets/gen-i/043Oddish.png",
  },
  {
    natdex: "044",
    name: "Gloom",
    type1: "grass",
    type2: "poison",
    imagesrc: "assets/gen-i/044Gloom.png",
  },
  {
    natdex: "045",
    name: "Vileplume",
    type1: "grass",
    type2: "poison",
    imagesrc: "assets/gen-i/045Vileplume.png",
  },
  {
    natdex: "046",
    name: "Paras",
    type1: "bug",
    type2: "grass",
    imagesrc: "assets/gen-i/046Paras.png",
  },
  {
    natdex: "047",
    name: "Parasect",
    type1: "bug",
    type2: "grass",
    imagesrc: "assets/gen-i/047Parasect.png",
  },
  {
    natdex: "048",
    name: "Venonat",
    type1: "bug",
    type2: "poison",
    imagesrc: "assets/gen-i/048Venonat.png",
  },
  {
    natdex: "049",
    name: "Venomoth",
    type1: "bug",
    type2: "poison",
    imagesrc: "assets/gen-i/049Venomoth.png",
  },
  {
    natdex: "050",
    name: "Diglett",
    type1: "ground",
    type2: "",
    imagesrc: "assets/gen-i/050Diglett.png",
  },
  {
    natdex: "051",
    name: "Dugtrio",
    type1: "ground",
    type2: "",
    imagesrc: "assets/gen-i/051Dugtrio.png",
  },
  {
    natdex: "052",
    name: "Meowth",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/052Meowth.png",
  },
  {
    natdex: "053",
    name: "Persian",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/053Persian.png",
  },
  {
    natdex: "054",
    name: "Psyduck",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/054Psyduck.png",
  },
  {
    natdex: "055",
    name: "Golduck",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/055Golduck.png",
  },
  {
    natdex: "056",
    name: "Mankey",
    type1: "fighting",
    type2: "",
    imagesrc: "assets/gen-i/056Mankey.png",
  },
  {
    natdex: "057",
    name: "Primeape",
    type1: "fighting",
    type2: "",
    imagesrc: "assets/gen-i/057Primeape.png",
  },
  {
    natdex: "058",
    name: "Growlithe",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/058Growlithe.png",
  },
  {
    natdex: "059",
    name: "Arcanine",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/059Arcanine.png",
  },
  {
    natdex: "060",
    name: "Poliwag",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/060Poliwag.png",
  },
  {
    natdex: "061",
    name: "Poliwhirl",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/061Poliwhirl.png",
  },
  {
    natdex: "062",
    name: "Poliwrath",
    type1: "water",
    type2: "fighting",
    imagesrc: "assets/gen-i/062Poliwrath.png",
  },
  {
    natdex: "063",
    name: "Abra",
    type1: "psychic",
    type2: "",
    imagesrc: "assets/gen-i/063Abra.png",
  },
  // Add these after Abra (063) in your pokemon array:
  {
    natdex: "064",
    name: "Kadabra",
    type1: "psychic",
    type2: "",
    imagesrc: "assets/gen-i/064Kadabra.png",
  },
  {
    natdex: "065",
    name: "Alakazam",
    type1: "psychic",
    type2: "",
    imagesrc: "assets/gen-i/065Alakazam.png",
  },
  {
    natdex: "066",
    name: "Machop",
    type1: "fighting",
    type2: "",
    imagesrc: "assets/gen-i/066Machop.png",
  },
  {
    natdex: "067",
    name: "Machoke",
    type1: "fighting",
    type2: "",
    imagesrc: "assets/gen-i/067Machoke.png",
  },
  {
    natdex: "068",
    name: "Machamp",
    type1: "fighting",
    type2: "",
    imagesrc: "assets/gen-i/068Machamp.png",
  },
  {
    natdex: "069",
    name: "Bellsprout",
    type1: "grass",
    type2: "poison",
    imagesrc: "assets/gen-i/069Bellsprout.png",
  },
  {
    natdex: "070",
    name: "Weepinbell",
    type1: "grass",
    type2: "poison",
    imagesrc: "assets/gen-i/070Weepinbell.png",
  },
  {
    natdex: "071",
    name: "Victreebel",
    type1: "grass",
    type2: "poison",
    imagesrc: "assets/gen-i/071Victreebel.png",
  },
  {
    natdex: "072",
    name: "Tentacool",
    type1: "water",
    type2: "poison",
    imagesrc: "assets/gen-i/072Tentacool.png",
  },
  {
    natdex: "073",
    name: "Tentacruel",
    type1: "water",
    type2: "poison",
    imagesrc: "assets/gen-i/073Tentacruel.png",
  },
  {
    natdex: "074",
    name: "Geodude",
    type1: "rock",
    type2: "ground",
    imagesrc: "assets/gen-i/074Geodude.png",
  },
  {
    natdex: "075",
    name: "Graveler",
    type1: "rock",
    type2: "ground",
    imagesrc: "assets/gen-i/075Graveler.png",
  },
  {
    natdex: "076",
    name: "Golem",
    type1: "rock",
    type2: "ground",
    imagesrc: "assets/gen-i/076Golem.png",
  },
  {
    natdex: "077",
    name: "Ponyta",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/077Ponyta.png",
  },
  {
    natdex: "078",
    name: "Rapidash",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/078Rapidash.png",
  },
  {
    natdex: "079",
    name: "Slowpoke",
    type1: "water",
    type2: "psychic",
    imagesrc: "assets/gen-i/079Slowpoke.png",
  },
  {
    natdex: "080",
    name: "Slowbro",
    type1: "water",
    type2: "psychic",
    imagesrc: "assets/gen-i/080Slowbro.png",
  },
  {
    natdex: "081",
    name: "Magnemite",
    type1: "electric",
    type2: "steel",
    imagesrc: "assets/gen-i/081Magnemite.png",
  },
  {
    natdex: "082",
    name: "Magneton",
    type1: "electric",
    type2: "steel",
    imagesrc: "assets/gen-i/082Magneton.png",
  },
  {
    natdex: "083",
    name: "Farfetch'd",
    type1: "normal",
    type2: "flying",
    imagesrc: "assets/gen-i/083Farfetchd.png",
  },
  {
    natdex: "084",
    name: "Doduo",
    type1: "normal",
    type2: "flying",
    imagesrc: "assets/gen-i/084Doduo.png",
  },
  {
    natdex: "085",
    name: "Dodrio",
    type1: "normal",
    type2: "flying",
    imagesrc: "assets/gen-i/085Dodrio.png",
  },
  {
    natdex: "086",
    name: "Seel",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/086Seel.png",
  },
  {
    natdex: "087",
    name: "Dewgong",
    type1: "water",
    type2: "ice",
    imagesrc: "assets/gen-i/087Dewgong.png",
  },
  {
    natdex: "088",
    name: "Grimer",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/088Grimer.png",
  },
  {
    natdex: "089",
    name: "Muk",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/089Muk.png",
  },
  {
    natdex: "090",
    name: "Shellder",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/090Shellder.png",
  },
  {
    natdex: "091",
    name: "Cloyster",
    type1: "water",
    type2: "ice",
    imagesrc: "assets/gen-i/091Cloyster.png",
  },
  {
    natdex: "092",
    name: "Gastly",
    type1: "ghost",
    type2: "poison",
    imagesrc: "assets/gen-i/092Gastly.png",
  },
  {
    natdex: "093",
    name: "Haunter",
    type1: "ghost",
    type2: "poison",
    imagesrc: "assets/gen-i/093Haunter.png",
  },
  {
    natdex: "094",
    name: "Gengar",
    type1: "ghost",
    type2: "poison",
    imagesrc: "assets/gen-i/094Gengar.png",
  },
  {
    natdex: "095",
    name: "Onix",
    type1: "rock",
    type2: "ground",
    imagesrc: "assets/gen-i/095Onix.png",
  },
  {
    natdex: "096",
    name: "Drowzee",
    type1: "psychic",
    type2: "",
    imagesrc: "assets/gen-i/096Drowzee.png",
  },
  {
    natdex: "097",
    name: "Hypno",
    type1: "psychic",
    type2: "",
    imagesrc: "assets/gen-i/097Hypno.png",
  },
  {
    natdex: "098",
    name: "Krabby",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/098Krabby.png",
  },
  {
    natdex: "099",
    name: "Kingler",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/099Kingler.png",
  },
  {
    natdex: "100",
    name: "Voltorb",
    type1: "electric",
    type2: "",
    imagesrc: "assets/gen-i/100Voltorb.png",
  },
  {
    natdex: "101",
    name: "Electrode",
    type1: "electric",
    type2: "",
    imagesrc: "assets/gen-i/101Electrode.png",
  },
  {
    natdex: "102",
    name: "Exeggcute",
    type1: "grass",
    type2: "psychic",
    imagesrc: "assets/gen-i/102Exeggcute.png",
  },
  {
    natdex: "103",
    name: "Exeggutor",
    type1: "grass",
    type2: "psychic",
    imagesrc: "assets/gen-i/103Exeggutor.png",
  },
  {
    natdex: "104",
    name: "Cubone",
    type1: "ground",
    type2: "",
    imagesrc: "assets/gen-i/104Cubone.png",
  },
  {
    natdex: "105",
    name: "Marowak",
    type1: "ground",
    type2: "",
    imagesrc: "assets/gen-i/105Marowak.png",
  },
  {
    natdex: "106",
    name: "Hitmonlee",
    type1: "fighting",
    type2: "",
    imagesrc: "assets/gen-i/106Hitmonlee.png",
  },
  {
    natdex: "107",
    name: "Hitmonchan",
    type1: "fighting",
    type2: "",
    imagesrc: "assets/gen-i/107Hitmonchan.png",
  },
  {
    natdex: "108",
    name: "Lickitung",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/108Lickitung.png",
  },
  {
    natdex: "109",
    name: "Koffing",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/109Koffing.png",
  },
  {
    natdex: "110",
    name: "Weezing",
    type1: "poison",
    type2: "",
    imagesrc: "assets/gen-i/110Weezing.png",
  },
  {
    natdex: "111",
    name: "Rhyhorn",
    type1: "ground",
    type2: "rock",
    imagesrc: "assets/gen-i/111Rhyhorn.png",
  },
  {
    natdex: "112",
    name: "Rhydon",
    type1: "ground",
    type2: "rock",
    imagesrc: "assets/gen-i/112Rhydon.png",
  },
  {
    natdex: "113",
    name: "Chansey",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/113Chansey.png",
  },
  {
    natdex: "114",
    name: "Tangela",
    type1: "grass",
    type2: "",
    imagesrc: "assets/gen-i/114Tangela.png",
  },
  {
    natdex: "115",
    name: "Kangaskhan",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/115Kangaskhan.png",
  },
  {
    natdex: "116",
    name: "Horsea",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/116Horsea.png",
  },
  {
    natdex: "117",
    name: "Seadra",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/117Seadra.png",
  },
  {
    natdex: "118",
    name: "Goldeen",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/118Goldeen.png",
  },
  {
    natdex: "119",
    name: "Seaking",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/119Seaking.png",
  },
  {
    natdex: "120",
    name: "Staryu",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/120Staryu.png",
  },
  {
    natdex: "121",
    name: "Starmie",
    type1: "water",
    type2: "psychic",
    imagesrc: "assets/gen-i/121Starmie.png",
  },
  {
    natdex: "122",
    name: "Mr. Mime",
    type1: "psychic",
    type2: "fairy",
    imagesrc: "assets/gen-i/122MrMime.png",
  },
  {
    natdex: "123",
    name: "Scyther",
    type1: "bug",
    type2: "flying",
    imagesrc: "assets/gen-i/123Scyther.png",
  },
  {
    natdex: "124",
    name: "Jynx",
    type1: "ice",
    type2: "psychic",
    imagesrc: "assets/gen-i/124Jynx.png",
  },
  {
    natdex: "125",
    name: "Electabuzz",
    type1: "electric",
    type2: "",
    imagesrc: "assets/gen-i/125Electabuzz.png",
  },
  {
    natdex: "126",
    name: "Magmar",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/126Magmar.png",
  },
  {
    natdex: "127",
    name: "Pinsir",
    type1: "bug",
    type2: "",
    imagesrc: "assets/gen-i/127Pinsir.png",
  },
  {
    natdex: "128",
    name: "Tauros",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/128Tauros.png",
  },
  {
    natdex: "129",
    name: "Magikarp",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/129Magikarp.png",
  },
  {
    natdex: "130",
    name: "Gyarados",
    type1: "water",
    type2: "flying",
    imagesrc: "assets/gen-i/130Gyarados.png",
  },
  {
    natdex: "131",
    name: "Lapras",
    type1: "water",
    type2: "ice",
    imagesrc: "assets/gen-i/131Lapras.png",
  },
  {
    natdex: "132",
    name: "Ditto",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/132Ditto.png",
  },
  {
    natdex: "133",
    name: "Eevee",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/133Eevee.png",
  },
  {
    natdex: "134",
    name: "Vaporeon",
    type1: "water",
    type2: "",
    imagesrc: "assets/gen-i/134Vaporeon.png",
  },
  {
    natdex: "135",
    name: "Jolteon",
    type1: "electric",
    type2: "",
    imagesrc: "assets/gen-i/135Jolteon.png",
  },
  {
    natdex: "136",
    name: "Flareon",
    type1: "fire",
    type2: "",
    imagesrc: "assets/gen-i/136Flareon.png",
  },
  {
    natdex: "137",
    name: "Porygon",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/137Porygon.png",
  },
  {
    natdex: "138",
    name: "Omanyte",
    type1: "rock",
    type2: "water",
    imagesrc: "assets/gen-i/138Omanyte.png",
  },
  {
    natdex: "139",
    name: "Omastar",
    type1: "rock",
    type2: "water",
    imagesrc: "assets/gen-i/139Omastar.png",
  },
  {
    natdex: "140",
    name: "Kabuto",
    type1: "rock",
    type2: "water",
    imagesrc: "assets/gen-i/140Kabuto.png",
  },
  {
    natdex: "141",
    name: "Kabutops",
    type1: "rock",
    type2: "water",
    imagesrc: "assets/gen-i/141Kabutops.png",
  },
  {
    natdex: "142",
    name: "Aerodactyl",
    type1: "rock",
    type2: "flying",
    imagesrc: "assets/gen-i/142Aerodactyl.png",
  },
  {
    natdex: "143",
    name: "Snorlax",
    type1: "normal",
    type2: "",
    imagesrc: "assets/gen-i/143Snorlax.png",
  },
  {
    natdex: "144",
    name: "Articuno",
    type1: "ice",
    type2: "flying",
    imagesrc: "assets/gen-i/144Articuno.png",
  },
  {
    natdex: "145",
    name: "Zapdos",
    type1: "electric",
    type2: "flying",
    imagesrc: "assets/gen-i/145Zapdos.png",
  },
  {
    natdex: "146",
    name: "Moltres",
    type1: "fire",
    type2: "flying",
    imagesrc: "assets/gen-i/146Moltres.png",
  },
  {
    natdex: "147",
    name: "Dratini",
    type1: "dragon",
    type2: "",
    imagesrc: "assets/gen-i/147Dratini.png",
  },
  {
    natdex: "148",
    name: "Dragonair",
    type1: "dragon",
    type2: "",
    imagesrc: "assets/gen-i/148Dragonair.png",
  },
  {
    natdex: "149",
    name: "Dragonite",
    type1: "dragon",
    type2: "flying",
    imagesrc: "assets/gen-i/149Dragonite.png",
  },
  {
    natdex: "150",
    name: "Mewtwo",
    type1: "psychic",
    type2: "",
    imagesrc: "assets/gen-i/150Mewtwo.png",
  },
  {
    natdex: "151",
    name: "Mew",
    type1: "psychic",
    type2: "",
    imagesrc: "assets/gen-i/151Mew.png",
  },
];

//Background color geneator
function getBackground(type1, type2) {
  if (!type2) {
    return `var(--${type1})`;
  }
  return `linear-gradient(var(--${type1}) 0%, var(--${type2}) 100%)`;
}

// Dex card generators

const dexContainer = document.getElementById("dex");

pokemon.forEach((p) => {
  const bg = getBackground(p.type1, p.type2);

  const card = document.createElement("div");
  card.classList.add("mon");
  card.style.background = bg;

  card.innerHTML = `
    <img src="${p.imagesrc}" alt ="${p.name}">
    <div class="monInfo">
    <span class="monNumber">${p.natdex}</span>
    <span class="monName">${p.name}</span>
    </div>
    `;

  dexContainer.appendChild(card);
});

//old generator work
// for (var i = 0; i < pokemon.length; i++) {
//   console.log(pokemon[i].natdex)
// }

/* <div class="mon grass-poison"><img src="assets/gen-i/001Bulbasaur.png" alt="Bulbasaur"><br>001 Bulbasaur</div> */

// Left to Do:

// Error handling for images
